Repository G1int/Glint_FE, pull requests merged in 2024-07, with the labels that each got.

#26 Feat/#17 modal detail 제작
  src/App.tsx
  src/assets/images/IMG_4494.jpg
  src/atoms/common.ts
  src/components/badge/Badge.styled.ts
  src/components/badge/Badge.tsx
  src/components/badge/index.ts
  src/components/buttons/Button.styled.ts
  src/components/buttons/Button.tsx
  src/components/index.ts
  src/components/modal/Modal.styled.ts
  src/components/modal/Modal.tsx
  src/components/modal/baseModal/BaseModal.styled.ts
  src/components/modal/baseModal/BaseModal.tsx
  src/components/modal/baseModal/index.ts
  src/components/modal/confirmModal/ConfirmModal.styled.ts
  src/components/modal/confirmModal/ConfirmModal.tsx
  src/components/modal/confirmModal/index.ts
  src/components/modal/index.ts
  src/components/modal/profileModal/ProfileModal.styled.ts
  src/components/modal/profileModal/ProfileModal.tsx
  src/components/modal/profileModal/index.ts
  src/components/toggle/Toggle.styled.ts
  src/hooks/index.ts
  src/hooks/useBadge.ts
  src/hooks/useModal.ts
  src/pages/home/Home.tsx
  src/pages/home/HomeDummy.tsx
  src/types/common/badge.ts
  src/types/common/index.ts
  src/types/common/modal.ts
  vite.config.ts
Labels: Feat

#28 Feat/#25 dialog hook 제작
  src/components/dialog/Dialog.tsx
  src/components/dialog/index.ts
  src/components/index.ts
  src/hooks/index.ts
  src/hooks/useDialog.ts
  src/pages/home/Home.tsx
Labels: Feat

#31 Feat/#29 badge 컴포넌트 제작
  src/components/badge/Badge.styled.ts
  src/components/badge/Badge.tsx
  src/hooks/useBadge.ts
  src/pages/home/Home.tsx
  tsconfig.json
Labels: Feat

#32 Feat/#30 layout 설정
  src/components/index.ts
  src/components/layout/Layout.styled.ts
  src/components/layout/Layout.tsx
  src/components/layout/index.ts
  src/components/router/Router.tsx
  src/pages/index.ts
  src/pages/signup/Signup.tsx
  src/pages/signup/index.ts
Labels: Feat

#33 Feat/#30 회원가입 스크린 제작
  src/App.tsx
  src/assets/icons/ic_check.svg
  src/assets/icons/ic_chevronLeft.svg
  src/assets/icons/ic_circleClose.svg
  src/assets/icons/index.ts
  src/components/buttons/Button.styled.ts
  src/components/buttons/Button.tsx
  src/components/input/Input.styled.ts
  src/components/input/formInput/FormInput.tsx
  src/components/layout/backLayout/BackLayout.styled.ts
  src/components/layout/backLayout/BackLayout.tsx
  src/components/layout/backLayout/index.ts
  src/components/layout/index.ts
  src/pages/signup/Signup.styled.ts
  src/pages/signup/Signup.tsx
  src/pages/signup/contatiners/index.ts
  src/pages/signup/contatiners/progressBar/ProgressBar.styled.ts
  src/pages/signup/contatiners/progressBar/ProgressBar.tsx
  src/pages/signup/contatiners/progressBar/index.ts
  src/pages/signup/contatiners/signupBirth/SignupBirth.tsx
  src/pages/signup/contatiners/signupBirth/index.ts
  src/pages/signup/contatiners/signupGender/SignupGender.tsx
  src/pages/signup/contatiners/signupGender/index.ts
  src/pages/signup/contatiners/signupHeight/SignupHeight.tsx
  src/pages/signup/contatiners/signupHeight/index.ts
  src/pages/signup/contatiners/signupNickname/SignupNickname.tsx
  src/pages/signup/contatiners/signupNickname/index.ts
  src/pages/signup/contatiners/signupProfile/SignupProfile.tsx
  src/pages/signup/contatiners/signupProfile/index.ts
  src/styles/index.ts
  src/styles/themes/colors.ts
  src/styles/themes/fonts.ts
  src/styles/themes/index.ts
  src/styles/themes/theme.ts
  src/types/domain/index.ts
  src/types/domain/signup/index.ts
  src/types/domain/signup/signup.ts
  src/types/index.ts
  src/utils/index.ts
  src/utils/number.ts
Labels: Feat

#35 Feat/#27 카카오 소셜로그인 구현
  index.html
  src/assets/icons/ic_kakaoLogin.svg
  src/assets/icons/index.ts
  src/components/index.ts
  src/components/router/AuthRoute.tsx
  src/components/router/Router.tsx
  src/components/socialLogin/index.ts
  src/components/socialLogin/kakao/KakaoLogin.styled.ts
  src/components/socialLogin/kakao/KakaoLogin.tsx
  src/components/socialLogin/kakao/KakaoLogout.tsx
  src/components/socialLogin/kakao/index.ts
  src/config/index.ts
  src/pages/auth/Auth.tsx
  src/pages/auth/index.ts
  src/pages/home/Home.tsx
  src/pages/index.ts
  src/pages/login/Login.styled.ts
  src/pages/login/Login.tsx
  src/pages/login/index.ts
Labels: Feat

#37 Feat/#36 캐로셀 오류 수정
  src/components/carousel/Carousel.tsx
  src/components/socialLogin/kakao/KakaoLogin.styled.ts
Labels: Feat

#39 Style/#38 캐로셀 컴포넌트 수정
  src/assets/index.ts
  src/assets/statics/index.ts
  src/assets/statics/landing.tsx
  src/components/carousel/Carousel.styled.ts
  src/components/carousel/Carousel.tsx
  src/components/carousel/carouselItem/CarouselItem.styled.ts
  src/components/carousel/carouselItem/CarouselItem.tsx
  src/components/router/Router.tsx
  src/pages/home/Home.tsx
  src/pages/home/HomeDummy.tsx
  src/pages/index.ts
  src/pages/login/Login.styled.ts
  src/pages/login/Login.tsx
  src/pages/login/index.ts
  src/pages/signup/contatiners/progressBar/ProgressBar.styled.ts
  src/styles/themes/colors.ts
Labels: Feat, Style

#44 Feat/#43 모달컴포넌트 수정
  src/assets/icons/ic_chevronRight.svg
  src/assets/icons/index.ts
  src/components/buttons/Button.styled.ts
  src/components/buttons/Button.tsx
  src/components/carousel/Carousel.styled.ts
  src/components/carousel/Carousel.tsx
  src/components/modal/baseModal/BaseModal.styled.ts
  src/components/modal/confirmModal/ConfirmModal.styled.ts
  src/components/modal/confirmModal/ConfirmModal.tsx
  src/styles/themes/colors.ts
Labels: Feat, Style

#49 Style/#47 디자인 시스템 작성
  src/assets/fonts/SUIT-Bold.woff2
  src/assets/fonts/SUIT-ExtraBold.woff2
  src/assets/fonts/SUIT-ExtraLight.woff2
  src/assets/fonts/SUIT-Heavy.woff2
  src/assets/fonts/SUIT-Light.woff2
  src/assets/fonts/SUIT-Medium.woff2
  src/assets/fonts/SUIT-Regular.woff2
  src/assets/fonts/SUIT-SemiBold.woff2
  src/assets/fonts/SUIT-Thin.woff2
  src/styles/fonts.css
  src/styles/themes/fonts.ts
Labels: Style

#52 Feat/#45 footer제작
  src/assets/icons/ic_home.svg
  src/assets/icons/ic_myInfo.svg
  src/assets/icons/ic_myMeeting.svg
  src/assets/icons/ic_search.svg
  src/assets/icons/index.ts
  src/components/buttons/Button.styled.ts
  src/components/formRadioButton/FormRadioButton.styled.ts
  src/components/layout/Layout.tsx
  src/components/layout/footer/Footer.styled.ts
  src/components/layout/footer/Footer.tsx
  src/components/layout/footer/index.ts
  src/components/layout/index.ts
  src/components/modal/confirmModal/ConfirmModal.styled.ts
  src/components/router/Router.tsx
  src/pages/home/Home.tsx
  src/pages/home/index.ts
  src/pages/index.ts
  src/pages/login/Login.tsx
  src/pages/signup/Signup.styled.ts
  src/styles/themes/colors.ts
Labels: Feat, Style

#53 Feat/#48 드롭다운 컴포넌트 제작
  src/components/dropdown/Dropdown.styled.ts
  src/components/dropdown/Dropdown.tsx
  src/components/dropdown/index.ts
  src/components/index.ts
  src/pages/home/Home.tsx
Labels: Feat

#58 style: 토스트 컴포넌트 디자인 시스템에 따라 수정 (#56)
  src/components/toast/Toast.styled.ts
  src/components/toast/toastItem/ToastItem.styled.ts
Labels: Style

#59 style: 뱃지컴포넌트 디자인 시스템에 따라 수정 (#57)
  src/components/badge/Badge.styled.ts
Labels: Style

#54 Feat/#51 내정보 스크린 제작
  src/assets/icons/ic_authBadge.svg
  src/assets/icons/ic_friendsManage.svg
  src/assets/icons/ic_myProfile.svg
  src/assets/icons/ic_profileCamera.svg
  src/assets/icons/index.ts
  src/assets/statics/index.ts
  src/assets/statics/myInfo.tsx
  src/components/layout/footer/Footer.tsx
  src/components/profile/Profile.styled.ts
  src/components/profile/Profile.tsx
  src/components/router/Router.tsx
  src/components/socialLogin/kakao/KakaoLogout.tsx
  src/components/toggle/Toggle.styled.ts
  src/components/toggle/Toggle.tsx
  src/pages/index.ts
  src/pages/myInfo/MyInfo.styled.ts
  src/pages/myInfo/MyInfo.tsx
  src/pages/myInfo/index.ts
  src/types/common/toast.ts
Labels: Feat

#60 feat: 카카오 로그인 서버로 인가코드 보내고 정보 받아오기로 수정 (#55)
  src/apis/user.ts
  src/components/socialLogin/kakao/KakaoLogout.tsx
  src/config/index.ts
  src/pages/auth/Auth.tsx
  src/types/domain/index.ts
  src/types/domain/login/index.ts
  src/types/domain/login/login.ts
Labels: Feat

#62 Feat/#46 회원가입 api 연동
  src/apis/axios.ts
  src/apis/common.ts
  src/apis/index.ts
  src/apis/signup.ts
  src/assets/icons/ic_user.svg
  src/assets/icons/index.ts
  src/assets/statics/index.ts
  src/assets/statics/radio.ts
  src/components/formRadioButton/FormRadioButton.tsx
  src/pages/signup/Signup.styled.ts
  src/pages/signup/Signup.tsx
  src/pages/signup/contatiners/signupGender/SignupGender.tsx
  src/pages/signup/contatiners/signupProfile/SignupProfile.tsx
  src/services/common.ts
  src/services/index.ts
  src/services/signup.ts
  src/types/common/image.ts
  src/types/common/index.ts
  src/types/domain/signup/signup.ts
Labels: Feat

#64 Feat/#61 메인페이지 스크린제작
  src/assets/icons/ic_add.svg
  src/assets/icons/ic_bell.svg
  src/assets/icons/ic_filter.svg
  src/assets/icons/ic_government.svg
  src/assets/icons/ic_logo.svg
  src/assets/icons/ic_majorCompany.svg
  src/assets/icons/ic_more.svg
  src/assets/icons/ic_prestigiousUniversity.svg
  src/assets/icons/ic_publicCompany.svg
  src/assets/icons/ic_specializedJob.svg
  src/assets/icons/ic_thirties.svg
  src/assets/icons/ic_twenties.svg
  src/assets/icons/ic_universityStudent.svg
  src/assets/icons/index.ts
  src/assets/statics/index.ts
  src/assets/statics/main.tsx
  src/components/badge/Badge.styled.ts
  src/components/badge/Badge.tsx
  src/components/layout/footer/Footer.tsx
  src/components/layout/header/Header.styled.ts
  src/components/layout/header/Header.tsx
  src/components/layout/header/index.ts
  src/components/layout/index.ts
  src/components/router/Router.tsx
  src/components/toggle/Toggle.tsx
  src/pages/home/Home.tsx
  src/pages/home/index.ts
  src/pages/index.ts
  src/pages/login/Login.tsx
  src/pages/main/Main.styled.ts
  src/pages/main/Main.tsx
  src/pages/main/index.ts
  src/pages/myInfo/MyInfo.styled.ts
  src/pages/myInfo/MyInfo.tsx
Labels: Feat

#68 Style/#67 디자인시스템 수정
  src/components/badge/Badge.styled.ts
  src/components/buttons/Button.styled.ts
  src/components/buttons/Button.tsx
  src/components/carousel/Carousel.styled.ts
  src/components/carousel/carouselItem/CarouselItem.styled.ts
  src/components/formRadioButton/FormRadioButton.styled.ts
  src/components/input/Input.styled.ts
  src/components/layout/footer/Footer.styled.ts
  src/components/modal/confirmModal/ConfirmModal.styled.ts
  src/components/profile/Profile.styled.ts
  src/components/toast/toastItem/ToastItem.styled.ts
  src/components/toggle/Toggle.styled.ts
  src/pages/login/Login.styled.ts
  src/pages/main/Main.styled.ts
  src/pages/myInfo/MyInfo.styled.ts
  src/pages/signup/Signup.styled.ts
  src/pages/signup/contatiners/progressBar/ProgressBar.styled.ts
  src/styles/themes/colors.ts
  src/styles/themes/fonts.ts
Labels: Style

#69 style: 바뀐 아이콘 변경, 바뀐 아이콘 및 화면에 따른 화면 css 수정 (#66)
  src/assets/icons/ic_add.svg
  src/pages/main/Main.styled.ts
  src/pages/main/Main.tsx
Labels: Style

#72 Feat/#71 회원가입 api method 수정
  src/apis/signup.ts
  src/pages/signup/Signup.tsx
  src/services/signup.ts
  src/types/domain/signup/signup.ts
Labels: Feat

#73 Feat/#65 카카오로그인 수정
  src/apis/user.ts
  src/components/socialLogin/kakao/KakaoLogin.tsx
  src/pages/auth/Auth.tsx
  src/pages/login/Login.styled.ts
  src/services/user.ts
  src/types/domain/login/login.ts
Labels: Feat

#76 Feat/#63 채팅방 스크린 제작
  src/assets/icons/ic_back.svg
  src/assets/icons/ic_chevronLeft.svg
  src/assets/icons/ic_out.svg
  src/assets/icons/ic_share.svg
  src/assets/icons/ic_write.svg
  src/assets/icons/index.ts
  src/components/badge/Badge.tsx
  src/components/layout/Layout.tsx
  src/components/layout/backLayout/BackLayout.styled.ts
  src/components/layout/backLayout/BackLayout.tsx
  src/components/router/Router.tsx
  src/components/tab/Tab.styled.ts
  src/components/tab/Tab.tsx
  src/pages/index.ts
  src/pages/meeting/Meeting.styled.ts
  src/pages/meeting/Meeting.tsx
  src/pages/meeting/containers/application/Application.styled.ts
  src/pages/meeting/containers/application/Application.tsx
  src/pages/meeting/containers/application/index.ts
  src/pages/meeting/containers/chatting/Chatting.styled.ts
  src/pages/meeting/containers/chatting/Chatting.tsx
  src/pages/meeting/containers/chatting/index.ts
  src/pages/meeting/containers/home/Home.styled.ts
  src/pages/meeting/containers/home/Home.tsx
  src/pages/meeting/containers/home/index.ts
  src/pages/meeting/containers/index.ts
  src/pages/meeting/index.ts
Labels: Feat

#79 Feat: Textarea 컴포넌트 제작 (#78)
  src/components/input/index.ts
  src/components/input/textarea/Textarea.styled.ts
  src/components/input/textarea/Textarea.tsx
  src/components/input/textarea/index.ts
Labels: Feat

#81 Feat/#80 사는곳필터 제작
  src/apis/location.ts
  src/assets/icons/ic_close.svg
  src/assets/icons/ic_modalRectangle.svg
  src/assets/icons/index.ts
  src/components/buttons/Button.styled.ts
  src/components/modal/index.ts
  src/components/modal/locationModal/LocationModal.styled.ts
  src/components/modal/locationModal/LocationModal.tsx
  src/components/modal/locationModal/index.ts
  src/services/index.ts
  src/services/location.ts
Labels: Feat

#82 Feat/#70 프로필스크린 제작
  src/assets/icons/ic_company.svg
  src/assets/icons/ic_dropdownArrow.svg
  src/assets/icons/ic_lock.svg
  src/assets/icons/ic_school.svg
  src/assets/icons/ic_smallAuthBadge.svg
  src/assets/icons/ic_smallChevronRight.svg
  src/assets/icons/index.ts
  src/assets/statics/index.ts
  src/assets/statics/myInfo.tsx
  src/assets/statics/myProfile.tsx
  src/components/badge/Badge.tsx
  src/components/buttons/Button.styled.ts
  src/components/dropdown/Dropdown.styled.ts
  src/components/dropdown/Dropdown.tsx
  src/components/layout/Layout.tsx
  src/components/modal/profileModal/ProfileModal.styled.ts
  src/components/modal/profileModal/ProfileModal.tsx
  src/components/router/Router.tsx
  src/pages/index.ts
  src/pages/main/Main.tsx
  src/pages/myInfo/MyInfo.styled.ts
  src/pages/myInfo/MyInfo.tsx
  src/pages/myProfile/MyProfile.styled.ts
  src/pages/myProfile/MyProfile.tsx
  src/pages/myProfile/index.ts
Labels: Feat

#86 Feat/#77 채팅 api 연동
  package-lock.json
  package.json
  src/apis/index.ts
  src/apis/meeting.ts
  src/components/tab/Tab.styled.ts
  src/config/index.ts
  src/pages/meeting/Meeting.styled.ts
  src/pages/meeting/Meeting.tsx
  src/pages/meeting/containers/chatting/Chatting.styled.ts
  src/pages/meeting/containers/chatting/Chatting.tsx
  src/pages/meeting/containers/home/Home.styled.ts
  src/pages/meeting/containers/home/Home.tsx
  src/services/index.ts
  src/services/meeting.ts
  src/types/domain/index.ts
  src/types/domain/meeting/index.ts
  src/types/domain/meeting/meeting.ts
  src/utils/date.ts
  src/utils/index.ts
Labels: Feat

#89 Feat/#84 회원가입 여부 체크
  src/apis/user.ts
  src/components/router/AuthRoute.tsx
  src/components/router/Router.tsx
  src/pages/auth/Auth.tsx
  src/services/user.ts
  src/types/domain/index.ts
  src/types/domain/user/index.ts
  src/types/domain/user/user.ts
Labels: Feat

#88 Feat/#85 드롭다운 컴포넌트 수정
  src/components/dropdown/Dropdown.styled.ts
  src/components/dropdown/Dropdown.tsx
Labels: Feat

#92 Feat/#91 미팅카드 컴포넌트 제작
  src/components/card/index.ts
  src/components/card/meetingCard/MeetingCard.styled.ts
  src/components/card/meetingCard/MeetingCard.tsx
  src/components/card/meetingCard/index.ts
  src/components/index.ts
  src/pages/main/Main.styled.ts
  src/pages/main/Main.tsx
Labels: Feat

#93 Feat/#90 검색 스크린 제작
  src/apis/user.ts
  src/assets/icons/ic_searchBlack.svg
  src/assets/icons/ic_searchGray.svg
  src/assets/icons/index.ts
  src/components/layout/footer/Footer.tsx
  src/components/modal/locationModal/LocationModal.styled.ts
  src/components/modal/locationModal/LocationModal.tsx
  src/components/router/Router.tsx
  src/pages/index.ts
  src/pages/search/Search.styled.ts
  src/pages/search/Search.tsx
  src/pages/search/index.ts
  src/services/user.ts
Labels: Feat

#94 Feat/#87 미팅방 만들기 스크린제작 및 api 연동
  package-lock.json
  package.json
  src/apis/createRoom.ts
  src/apis/index.ts
  src/assets/statics/createRoom.ts
  src/assets/statics/index.ts
  src/assets/statics/myProfile.tsx
  src/assets/statics/radio.ts
  src/components/badge/Badge.styled.ts
  src/components/badge/Badge.tsx
  src/components/dropdown/Dropdown.tsx
  src/components/formRadioButton/FormRadioButton.styled.ts
  src/components/formRadioButton/FormRadioButton.tsx
  src/components/input/textarea/Textarea.tsx
  src/components/layout/Layout.tsx
  src/components/layout/backLayout/BackLayout.styled.ts
  src/components/router/Router.tsx
  src/pages/createRoom/CreateRoom.styled.ts
  src/pages/createRoom/CreateRoom.tsx
  src/pages/createRoom/index.ts
  src/pages/index.ts
  src/pages/myProfile/MyProfile.tsx
  src/services/createRoom.ts
  src/services/index.ts
  src/types/domain/createRoom/createRoom.ts
  src/types/domain/createRoom/index.ts
  src/types/domain/index.ts
  vite.config.ts
Labels: Feat

#98 Feat/#97 range slider컴포넌트 제작
  src/components/index.ts
  src/components/rangeSlider/RangeSlider.styled.ts
  src/components/rangeSlider/RangeSlider.tsx
  src/components/rangeSlider/index.ts
Labels: Feat

#100 Feat/#99 내미팅 스크린 제작
  src/components/router/Router.tsx
  src/components/tab/Tab.styled.ts
  src/pages/index.ts
  src/pages/myMeeting/MyMeeting.styled.ts
  src/pages/myMeeting/MyMeeting.tsx
  src/pages/myMeeting/containers/index.ts
  src/pages/myMeeting/containers/joinMeeting/JoinMeeting.styled.ts
  src/pages/myMeeting/containers/joinMeeting/JoinMeeting.tsx
  src/pages/myMeeting/containers/joinMeeting/index.ts
  src/pages/myMeeting/containers/waitMeeting/WaitMeeing.styled.ts
  src/pages/myMeeting/containers/waitMeeting/WaitMeeting.tsx
  src/pages/myMeeting/containers/waitMeeting/index.ts
  src/pages/myMeeting/index.ts
Labels: Feat

#102 Feat/#101 메인 미팅목록 api연동
  src/apis/index.ts
  src/apis/main.ts
  src/components/card/meetingCard/MeetingCard.styled.ts
  src/components/card/meetingCard/MeetingCard.tsx
  src/pages/main/Main.styled.ts
  src/pages/main/Main.tsx
  src/services/index.ts
  src/services/main.ts
  src/types/domain/index.ts
  src/types/domain/main/index.ts
  src/types/domain/main/main.ts
Labels: Feat

#106 Feat/#104 내미팅 api연동
  src/apis/main.ts
  src/apis/meeting.ts
  src/components/card/meetingCard/MeetingCard.tsx
  src/pages/main/Main.tsx
  src/pages/myMeeting/MyMeeting.tsx
  src/pages/myMeeting/containers/joinMeeting/JoinMeeting.styled.ts
  src/pages/myMeeting/containers/joinMeeting/JoinMeeting.tsx
  src/pages/myMeeting/containers/waitMeeting/WaitMeeing.styled.ts
  src/pages/myMeeting/containers/waitMeeting/WaitMeeting.tsx
  src/services/main.ts
  src/services/meeting.ts
  src/types/domain/index.ts
  src/types/domain/main/index.ts
  src/types/domain/main/main.ts
  src/types/domain/meeting/meeting.ts
Labels: Feat

#107 Feat/#95 채팅 홈 스크린 제작
  src/apis/meeting.ts
  src/assets/icons/ic_circleStar.svg
  src/assets/icons/ic_info.svg
  src/assets/icons/ic_meetingWait.svg
  src/assets/icons/ic_unlock.svg
  src/assets/icons/index.ts
  src/pages/meeting/containers/home/Home.styled.ts
  src/pages/meeting/containers/home/Home.tsx
  src/pages/meeting/containers/home/containers/profile/Profile.styled.ts
  src/pages/meeting/containers/home/containers/profile/Profile.tsx
  src/pages/search/Search.tsx
  src/services/meeting.ts
  src/types/domain/meeting/meeting.ts
Labels: Feat

#109 Feat/#103 미팅검색 api연동
  src/apis/index.ts
  src/apis/keyword.ts
  src/apis/location.ts
  src/apis/meeting.ts
  src/pages/main/Main.tsx
  src/pages/search/Search.styled.ts
  src/pages/search/Search.tsx
  src/services/index.ts
  src/services/keyword.ts
  src/services/location.ts
  src/services/meeting.ts
  src/types/domain/meeting/meeting.ts
Labels: Feat

#111 Feat/#108 채팅 신청목록 api 연동
  src/apis/meeting.ts
  src/assets/icons/ic_sticker.svg
  src/assets/icons/index.ts
  src/components/buttons/Button.styled.ts
  src/components/buttons/Button.tsx
  src/pages/meeting/Meeting.tsx
  src/pages/meeting/containers/application/Application.styled.ts
  src/pages/meeting/containers/application/Application.tsx
  src/pages/meeting/containers/application/index.ts
  src/pages/meeting/containers/home/containers/profile/Profile.tsx
  src/pages/meeting/containers/index.ts
  src/pages/meeting/containers/join/Join.styled.ts
  src/pages/meeting/containers/join/Join.tsx
  src/pages/meeting/containers/join/index.ts
  src/services/meeting.ts
  src/types/common/button.ts
  src/types/common/index.ts
  src/types/domain/meeting/meeting.ts
Labels: Feat

#113 Feat/#112 배포 전 세팅
  index.html
  public/favicon.ico
  public/images/logo.png
  public/images/logo.svg
  public/images/logo_square_180.png
  public/images/logo_square_192.png
  robot.txt
  src/assets/images/IMG_4494.jpg
  src/assets/images/img_01.jpg
  src/assets/react.svg
Labels: Feat

#114 Feat/#110 로딩스피너,페이지 제작
  src/assets/icons/ic_404.svg
  src/assets/icons/ic_spinnerInner.svg
  src/assets/icons/ic_spinnerOuter.png
  src/assets/icons/index.ts
  src/components/index.ts
  src/components/layout/Layout.tsx
  src/components/layout/footer/Footer.tsx
  src/components/router/Router.tsx
  src/components/spinner/Spinner.styled.ts
  src/components/spinner/Spinner.tsx
  src/components/spinner/index.ts
  src/components/toast/Toast.styled.ts
  src/components/toast/Toast.tsx
  src/pages/404/Error404.styled.ts
  src/pages/404/Error404.tsx
  src/pages/404/index.ts
  src/pages/auth/Auth.tsx
  src/pages/index.ts
  src/pages/loading/Loading.styled.ts
  src/pages/loading/Loading.tsx
  src/pages/loading/index.ts
Labels: Feat

#121 Feat/#116 로그아웃api연동
  src/apis/axios.ts
  src/apis/user.ts
  src/components/socialLogin/kakao/KakaoLogout.tsx
  src/services/user.ts
Labels: Feat

#122 Feat/#117 회원탈퇴api연동
  src/apis/axios.ts
  src/apis/user.ts
  src/pages/myInfo/MyInfo.tsx
  src/pages/search/Search.tsx
  src/services/user.ts
Labels: Feat

#124 Feat/#115 미팅 수락, 거절, 방나가기 api 연동
  src/apis/keyword.ts
  src/apis/meeting.ts
  src/assets/icons/ic_chat.svg
  src/assets/icons/index.ts
  src/components/badge/Badge.styled.ts
  src/components/layout/backLayout/BackLayout.styled.ts
  src/components/layout/backLayout/BackLayout.tsx
  src/components/modal/baseModal/BaseModal.styled.ts
  src/components/tab/Tab.styled.ts
  src/components/tab/Tab.tsx
  src/hooks/useModal.ts
  src/pages/createRoom/CreateRoom.styled.ts
  src/pages/createRoom/CreateRoom.tsx
  src/pages/meeting/Meeting.styled.ts
  src/pages/meeting/Meeting.tsx
  src/pages/meeting/containers/chatting/Chatting.styled.ts
  src/pages/meeting/containers/chatting/Chatting.tsx
  src/pages/meeting/containers/home/Home.tsx
  src/pages/meeting/containers/home/containers/profile/Profile.styled.ts
  src/pages/meeting/containers/home/containers/profile/Profile.tsx
  src/pages/meeting/containers/join/Join.styled.ts
  src/pages/meeting/containers/join/Join.tsx
  src/pages/search/Search.tsx
  src/services/keyword.ts
  src/services/meeting.ts
  src/types/domain/meeting/meeting.ts
Labels: Feat

#127 Feat/#123 회원가입여부 수정
  src/apis/user.ts
  src/pages/auth/Auth.tsx
  src/services/user.ts
  src/types/domain/login/login.ts
  src/types/domain/user/user.ts
Labels: Feat

#130 Feat/#129 toast처리
  src/apis/meeting.ts
  src/components/modal/confirmModal/ConfirmModal.styled.ts
  src/components/modal/confirmModal/ConfirmModal.tsx
  src/components/socialLogin/kakao/KakaoLogout.tsx
  src/hooks/useUserInfo.ts
  src/pages/auth/Auth.tsx
  src/pages/main/Main.tsx
  src/pages/meeting/Meeting.tsx
  src/pages/myInfo/MyInfo.tsx
  src/pages/myMeeting/containers/joinMeeting/JoinMeeting.styled.ts
  src/pages/myMeeting/containers/joinMeeting/JoinMeeting.tsx
  src/pages/myMeeting/containers/waitMeeting/WaitMeeing.styled.ts
  src/pages/myMeeting/containers/waitMeeting/WaitMeeting.tsx
  src/pages/myProfile/MyProfile.tsx
  src/pages/search/Search.tsx
  src/services/keyword.ts
Labels: Feat

#133 Feat/#128 MultiLocationModal 이슈 수정
  src/components/modal/multiLocationModal/MultiLocationModal.tsx
Labels: Feat

#135 Feat/#128 회사, 학교 입력 기능 추가
  src/pages/createRoom/CreateRoom.styled.ts
  src/pages/createRoom/CreateRoom.tsx
  src/pages/meeting/containers/chatting/Chatting.tsx
Labels: Feat

#137 fix: vercel.json 파일 추가 (#136)
  vercel.json
Labels: Fix

#138 Feat/#134 프로필 옵션 수정
  public/images/meetingRoom/meetingImg1.png
  public/images/meetingRoom/meetingImg2.png
  src/assets/statics/index.ts
  src/assets/statics/meetingCard.tsx
  src/components/card/meetingCard/MeetingCard.tsx
  src/components/profile/Profile.styled.ts
  src/components/profile/Profile.tsx
  src/pages/myProfile/MyProfile.tsx
Labels: Feat

#140 Feat/#139 회원가입 미팅방 이슈 수정
  src/components/modal/multiLocationModal/MultiLocationModal.tsx
  src/pages/createRoom/CreateRoom.styled.ts
  src/pages/createRoom/CreateRoom.tsx
  src/pages/createRoom/hooks/useCreateRoom.ts
  src/pages/signup/Signup.styled.ts
  src/pages/signup/contatiners/signupGender/SignupGender.tsx
Labels: Feat

#141 Feat/#132 지역선택 필터적용
  src/apis/meeting.ts
  src/components/modal/multiLocationModal/MultiLocationModal.styled.ts
  src/pages/search/Search.styled.ts
  src/pages/search/Search.tsx
  src/services/meeting.ts
Labels: Feat

#143 Feat/#142 미팅방이미지추가
  public/images/meetingRoom/meetingImg1.png
  public/images/meetingRoom/meetingImg1.webp
  public/images/meetingRoom/meetingImg2.png
  public/images/meetingRoom/meetingImg2.webp
  public/images/meetingRoom/meetingImg3.webp
  public/images/meetingRoom/meetingImg4.webp
  src/assets/statics/meetingCard.tsx
  src/components/card/meetingCard/MeetingCard.tsx
Labels: Feat
